<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <None Include="../../native/win-x64/Sora.Acl.dll" Condition="Exists('../../native/win-x64/Sora.Acl.dll')" Link="Sora.Acl.dll" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="../../native-source/acl/**/*" Exclude="../../native-source/acl/positive-fixtures/**/*;../../native-source/acl/runtime-provenance/**/*" Link="native-source/acl/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="../../native/win-x64/Texture2DDecoderNative.dll" Condition="Exists('../../native/win-x64/Texture2DDecoderNative.dll')" Link="Texture2DDecoderNative.dll" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="../../LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="../../licenses/**/*" Link="licenses/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="../../docs/*.md" Link="docs/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
